### ISSUE TITLE
core-selected

### ISSUE THREAD

**Issue by nevir** [Polymer/paper-item#12]
We should consider having a default style/color for `.core-selected` (similar to [`core-item`](https://github.com/Polymer/core-item/blob/master/core-item.css#L21-23))

``` css
html /deep/ paper-item.core-selected {
  color: #e91e63;
}
```

maybe?
