### ISSUE TITLE
Still wrong height?

### ISSUE THREAD

**Issue by Wurper** [Polymer/paper-item#15]
Should the CSS rule height: 100% still be there?

``` css
polyfill-next-selector { content: '.button-content > a'; }
      ::content > a {
        height: 100%;
        /* flex */
        -ms-flex: 1 1 0.000000001px;
        -webkit-flex: 1;
        flex: 1;
        -webkit-flex-basis: 0.000000001px;
        flex-basis: 0.000000001px;
      }
```
